### ISSUE TITLE
Wrong example in README

### ISSUE THREAD

**Issue by Dinuuu** [Wolox/wor-authentication#6]
In the README file there is an example for `authenticate_entity` that is 
```ruby
# authentication_controller.rb
def authenticate_entity(params)
  user ||= User.find_by(email: params[:email])
  return nil unless user.present? && user.valid_password?(params[:password])
end
```
This method uses memoization when it shouldn't (in my opinion) and also returns `nil` always

**Comment by mishuagopian** [comment]
https://github.com/Wolox/wor-authentication/pull/10
