### ISSUE TITLE
Change in README

### ISSUE THREAD

**Issue by Dinuuu** [Wolox/wor-authentication#7]
```ruby
def new_token_expiration_date
  (Time.zone.now + 2.days).to_i
end

def token_maximum_useful_date
  (Time.zone.now + 30.days).to_i
end
```
In the methods listed above I wouldn't use `.to_i` because if you use it, you are not returning dates, just an integer, and also I would use the `from_now` method, for example, `2.days.from_now`

**Comment by mishuagopian** [comment]
We'll change this to an initializer, so it will be removed soon

**Comment by hdf1986** [comment]
Related to #2

**Comment by mishuagopian** [comment]
https://github.com/Wolox/wor-authentication/pull/12
