### ISSUE TITLE
Lost of generalization

### ISSUE THREAD

**Issue by Dinuuu** [Wolox/wor-authentication#8]
I think that the gem was created to add Authentication to any model that we want to, but in the README you are always talking about Users which may mislead some persons, for example: 
- "User tracking and custom validations"
- "Keeping track of users? Override..."
- "Invalidating all tokens for a user? "

**Comment by mishuagopian** [comment]
Yeah, agree 100%. I'll rewrite those!

**Comment by Dinuuu** [comment]
Cool! thxs @mishuagopian
